### PR TITLE
(feat) add toHaveStyleRule matcher

### PR DESCRIPTION
**Pull request by danreeves**
**What**: Adding a `.toHaveStyleRule()` match to jest.

**Why**: It provides an explicit way to test certain styles are applied.

**How**: Lots of inspiration (and code) from the `jest-styled-components` repo.

First time building anything for jest and using glamor beyond as a consumer of it. I would gladly take suggestions and improvements! 😁 

I would like to like to also implement a `.toHaveStyleRules({})` matcher which would take an css object, but figured I'd propose this one first.

Have a nice day!

### CODE REVIEW

**Comment by jameswlane** [comment]
This is super cool and useful. I had to make a hack helper utility to do this.

**Comment by danreeves** [comment]
Hey! Thanks for the feedback. 

It actually wasn't too tricky to support `enzyme.render`, so that's in there now.

I had to disable the complexity lint rule on `getClassNames` which I guess is at 7 now. Not sure if there's a better way to structure that one.

**Comment by kentcdodds** [comment]
> I had to disable the complexity lint rule on getClassNames which I guess is at 7 now

I should honestly just update that rule to allow for a complexity of 12 or something. It's more annoying than helpful. Thanks!

**Comment by kentcdodds** [comment]
I'm not sure what's up with the travis build... I'll give it a little more time...

**Comment by danreeves** [comment]
Thanks for merging! Any idea when this will be released?

**Comment by kentcdodds** [comment]
Sorry @danreeves, Travis was acting really strange on this repo yesterday and I use travis to automatically release new versions when PRs are merged. Hopefully [this build](https://travis-ci.org/kentcdodds/jest-glamor-react/builds/329715338) passes without a problem.

**Comment by danreeves** [comment]
Not a problem! 😅 Looks like it's gone out now 🎉 

Thanks again

**Comment by jameswlane** [comment]
@kentcdodds TravisCI has been having a lot of [issues](https://www.traviscistatus.com/) the last week. I have a PR that's been in queue in Travis for over six hours. I am moving some projects to [CircleCi](https://circleci.com/) to test their reliability.

**Comment by kentcdodds** [comment]
I've thought about doing that as well...

**Comment by jameswlane** [comment]
@kentcdodds I will drop you a message if you want later this week with my results. We have almost the same build process. You could cheat off my paper after I worked out all my bugs in the build process.

**Pull request merged**
