### PR TITLE
fix: replace css- prefixed selectors that don't have styles

### LINKED ISSUE #27: css- prefixed selectors are not replaced if the component has no styles
- `jest-glamor-react` version: 3.2.2
- `node` version: 8.9.0
- `npm` (or `yarn`) version: yarn 1.3.2

Relevant code or config

I created a [repo that demonstrates the problem](https://github.com/rszewczyk/glamor-jest-demo).

If a component that has selectors prefixed with `css-` but the component does not have any styles associated with those selectors, the selectors will not be replaced in the snapshot. I realize this sounds weird, but Emotion will add selectors like this when using its `styled` utility and the `babel-plugin-emotion`. 

You can see a contrived example [here](https://github.com/rszewczyk/glamor-jest-demo/blob/master/__snapshots__/components-glamor.test.js.snap). Note that as long as at least one selector has styles associated with it, all of the `css-` prefixed selectors get replaced. It's only when none of the selectors are in the stylesheet that it doesn't rewrite them.

[Here is an example with Emotion](https://github.com/rszewczyk/glamor-jest-demo/blob/master/__snapshots__/components-emotion.test.js.snap).

Suggested Fix:
I'm going to submit a PR shortly.

### PR DESCRIPTION
**Pull request by rszewczyk**
Fixes #27

**What**: Replace `css-` prefixed selectors even if there are no styles associated with the component in which those selectors are used.

**Why**: It's possible when using the `styled` utility from `react-emotion` that some generated selectors won't have associated styles. This leads to a confusing snapshot where some `css-` prefixed selectors are replaced and others aren't

**How**: Adds a test case and then modifies the serializer to replace selectors even when there are no styles. It also modifies the `replaceClassNames` function slightly so that extra lines aren't inserted in the case where there are no styles.

### CODE REVIEW

**Comment by kentcdodds** [comment]
Hmmm... I'm not 100% certain that I want this change. I don't really have a use case personally, but I think it would be confusing to have a class name changed if we don't show it in the CSS above. Do you know anyone else who wants this change?

**Comment by rszewczyk** [comment]
I don't, know anyone else, no (unless you count my co-workers as "else" 😄 )

As it stands the serializer will change classnames (without this change) even without styles if it appears alongside a selector that does have styles. E.g. this code (using Emotion and its associated Babel plugin and version 3.2.2 of `jest-glamor-react`):

```
import React from 'react'
import styled from 'react-emotion'

export const P = styled.p`
  color: ${props => (props.red ? 'red' : null)};
`
```

and this test:

```
import React from 'react'
import renderer from 'react-test-renderer'
import { P } from './components-emotion'
import serializer from 'jest-glamor-react'
import { sheet } from 'emotion'

expect.addSnapshotSerializer(
  serializer(sheet, (cn, index) => `emotion-${index}`)
)

it('renders as red', () => {
  expect(renderer.create(<P red />).toJSON()).toMatchSnapshot()
})

it('renders without red', () => {
  expect(renderer.create(<P />).toJSON()).toMatchSnapshot()
})
```

Produces this snapshot:

```
exports[`renders as red 1`] = `
.emotion-0 {
  color: red;
}

<p
  className="emotion-0 emotion-1"
/>
`;

exports[`renders without red 1`] = `
<p
  className="css-olgnlr css-lnhyjl0"
/>
`;
```

So, I think it would be less confusing the selectors were changed in both snapshots since they're both generated by emotion. I also think the tests would be a bit less fragile because the serializer insulates them from changes to whatever algorithm generates the `css-****` selectors.

However, I'm not aware of a case where you can get a selector with no styles using `glamor` (in my demo repo I had to contrive the `glamor` example. So I understand the hesitation.

**Comment by kentcdodds** [comment]
Would you be willing to make this configurable and default to disabled?

**Comment by rszewczyk** [comment]
That sounds like a reasonable compromise. I'll work on that. Thanks!

**Comment by mitchellhamilton** [comment]
Just wanted to mention that in the next major version of emotion we'll have `jest-emotion` which will do this and the prefix before the component selector classes will change.

**Comment by kentcdodds** [comment]
That's good enough for me @mitchellhamilton! Thanks!

**Comment by kentcdodds** [comment]
Sorry, I've made a bunch of changes and totally forgot about this PR. I'm pretty sure the original issue should be resolved in v4 though so I'm going to close this. Thanks!

**Pull request closed without merging**
