### PR TITLE
feat(matchers): support asymmetric matchers

### LINKED ISSUE #36: Support expect matchers on value field
* `jest-glamor-react` version: v4.2.1
* `node` version: v8.11.1
* `npm` (or `yarn`) version: v5.8.0

Relevant code or config

```javascript
it('could accept expect matchers', () => {
  expect(component).toHaveStyleRule('position', expect.anything());
});
```

https://github.com/kentcdodds/jest-glamor-react/blob/21fdeffd2de3a11430554f4be08ccc6562a17aa7/src/matchers.js#L6-L10

Problem description:
toHaveStyleRule accepts only `RegExp` or `String`

Suggested solution:
Add https://github.com/facebook/jest/tree/master/packages/expect as a dependency and use `expect` to check equivalence.

P.S. Could I make a PR for this?

### PR DESCRIPTION
**Pull request by Ailrun**
resolve #36

**What**: Support asymmetric matchers (#36)

**Why**: Using asymmetric matchers make tests easier

**How**: see https://github.com/facebook/jest/blob/be4bec387d90ac8d6a7596be88bf8e4994bc3ed9/packages/expect/src/jasmine_utils.js#L36

This can support `expect@^21 || ^22`, and `jest-matchers@^19 || ^20`, but I do not know how to add exclusive-or-ly those peerDeps. Is there a way to do so?

### CODE REVIEW

**Comment by Ailrun** [comment]
Oh, there're some coverage problems. I will add some tests...

**Comment by kentcdodds** [comment]
Actually, would you like to add documentation for this feature?

**Comment by kentcdodds** [comment]
Thanks so much for your help! I've added you as a collaborator on the project. Please make sure that you review the `other/MAINTAINING.md` and `CONTRIBUTING.md` files (specifically the bit about the commit messages and the git hooks) and familiarize yourself with the code of conduct (we're using [the contributor covenant](http://contributor-covenant.org/)). You might also want to [watch the repo](https://help.github.com/articles/watching-repositories/) to be notified when someone files an issue/PR. Please continue to make PRs as you feel the need (you can make your branches directly on the repo rather than your fork if you want). Thanks! And welcome to the team :)

**Comment by Ailrun** [comment]
@kentcdodds Oh, I miss that. Thank you for notifying me! I will add it after busy days...

**Pull request merged**
